import type { Metadata } from "next";
import localFont from 'next/font/local';
import "@/styles/globals.css";
import StoreProvider from "@/providers/StoreProvider";


const Dana = localFont({
  src: [
    {
      path: '../../public/assets/fonts/Dana-Regular.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/assets/fonts/Dana-Bold.woff',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-Dana',
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${Dana.variable} antialiased`}
      >
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
